### ISSUE TITLE
remove any 2020 data

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2021.alaoweb.org#39]
Remaining 2020 data as of Aug 2, 2021:
- [x] Awards time (config.yml)
- [x] Service Project (config.yml) #96
- [x] Website Build-Settings URL (config.yml)
- [x] Google Analytics (config.yml) #10
- [x] conference year (config.yml) 
- [x] Team page (CPC & Web team) #85

**Comment by kenirwin** [comment]
these settings have been updated through multiple pull requests and changes
